apiVersion: v1
kind: ServiceAccount
metadata:
  name: ansible-shell
  namespace: {{ kube_resource_namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: ansible-shell
  namespace: {{ kube_resource_namespace }}
rules:
  - apiGroups:
      - ""
      - apps
      - extensions
    resources:
      - configmaps
      - pods
      - secrets
      - namespaces
      - deployments
      - services
      - ingresses
      - endpoints
    verbs:
      - get
      - create
      - list
      - show
      - patch
      - update
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ansible-shell
  namespace: {{ kube_resource_namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ansible-shell
subjects:
  - kind: ServiceAccount
    name: ansible-shell
    namespace: {{ kube_resource_namespace }}

---
apiVersion: v1
kind: Pod
metadata:
  name: ansible-shell
  namespace: {{ kube_resource_namespace }}
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: ansible-shell
      # Normally container tag would come from inventory but we want to show changes over time
      image: willthames/ansible-kube-demo-shell:latest
      stdin: true
      tty: true

  serviceAccount: ansible-shell
